### ISSUE TITLE
고냥 궁금증

### ISSUE THREAD

**Issue by wurikiji** [depromeet/www.depromeet.com#1]
@danmin20  여기 ts 정의 선언할 때, string 으로 안하고 값으로 적어준 이유는 뭔가유?? 이렇게 하면 default 값으로 들어가나요?

https://github.com/depromeet/www.depromeet.com/blob/aff44fcd70155e627bee521282c6a8347d50c06a/styles/styled.d.ts#L3-L20

**Comment by wurikiji** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-merging.html
확인 완료.

**Comment by danmin20** [comment]
DefaultThene -> DefaultTheme으로 해야 먹는데 나중에 커밋 어멘드 하겠,,,
