### ISSUE TITLE
Recruitment detail carousel

### ISSUE THREAD

**Issue by sensecodevalue** [depromeet/www.depromeet.com#190]
라이브러리 그냥 사용할까....

**Comment by ding-co** [comment]
예압..

**Comment by hyesungoh** [comment]
https://github.com/depromeet/ahmatda-web/tree/main/src/components/carousel

코드 조각 공유드립니다 !!

---

근데 prev, next 버튼같은 로직은 없긴해요 ㅋㅋㅋㅋ

공통 컴포넌트로 제가 넣어도 좋습니다 !!

**Comment by ding-co** [comment]
[react-slick](https://www.npmjs.com/package/react-slick)

이 친구는 제가 좀 많이 써봤는데 깊이 쓸수록 스트레스를 주는 버그 투성이 친구입니다 ^^..

**Comment by sensecodevalue** [comment]
오호 react-responsive-carousel 요거 생각하긴랬었어요! 하지만 옮겨주신다면 정성스래 써보겠습니다!
