### ISSUE TITLE
custom cursor event off in mobile

### ISSUE THREAD

**Issue by sensecodevalue** [depromeet/www.depromeet.com#207]
모바일에서 클릭 터치 이벤트가 발생하면 커서가 찍혀보이는 이슈가 있어서 userAgent를 보고 해당 event를 붙이지 않는 방향을 고려중입니다!

**Comment by hyesungoh** [comment]
오오 저도 생각만 해뒀다가 까먹었엇는데 감사합니다 !!

아예 `CustomCursor` 컴포넌트를 안그려도 좋을 거 같아요 !
