### ISSUE TITLE
일부 폰트가 적용되지 않는 문제

### ISSUE THREAD

**Issue by minjongbaek** [depromeet/www.depromeet.com#329]
안녕하세요!

디프만 사이트에 Decimal 폰트 일부가 적용되지 않는 문제가 있는 것으로 보여요.

간단하게 확인해보니 오탈자 때문에 발생한 문제 같아요. 코드에 포함된 폰트는 `Decimal-Semibold.woff` 인데 `Decimal-SemiBold.woff` 폰트를 요청하고 있어요.

![image](https://github.com/depromeet/www.depromeet.com/assets/48359052/858d5864-868f-4a82-8e35-5909319f4e65)

**Comment by sumi-0011** [comment]
감사합니다! 빠르게 확인해보겠습니다 :D
