### ISSUE TITLE
FAQ 컴포넌트 리팩토링 (Headless, Testable)

### ISSUE THREAD

**Issue by kimyouknow** [depromeet/www.depromeet.com#335]
`FAQ 컴포넌트 리팩토링`

### 왜? 

> 요즘에 관심있는 분야가 생겼는데 찍먹해볼만한 적당한 프로젝트가 여기인듯!! 리뷰해줄 사람도 있고ㅎㅎ

- `Headless한 컴포넌트`에 관심이 생겼는데, 코드로 직접 작성해보고 싶어서 
  - 해드리스를 꼭 모든 곳에 적용할 필요는 없지만 `컴포넌트의 역할과 책임을 어떻게 설계할지` 고민해보기
- `Test에 관심`이 생겼는데, FAQ 컴포넌트가 요구사항도 적절하고 테스트 코드 짜볼만해서
  - 이것도 같은 맥락! `컴포넌트의 역할과 책임을 어떻게 설계할지` 고민해보기 (인터페이스, 의존성)

### 관련 글

**Testable**
- [테스트에 대한 오해와 사실](https://blog.jbee.io/developments/%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%97%90+%EB%8C%80%ED%95%9C+%EC%98%A4%ED%95%B4%EC%99%80+%EC%82%AC%EC%8B%A4) (테스트 코드가 왜 작성하기 어려운가, 테스트에 대한 저자가 생각하는 주요 포인트 5개)
- [프론트엔드 테스트 코드와 의존성](https://blog.jbee.io/developments/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C+%ED%85%8C%EC%8A%A4%ED%8A%B8+%EC%BD%94%EB%93%9C%EC%99%80+%EC%9D%98%EC%A1%B4%EC%84%B1) (프론트엔드 테스트 코드 환경, 의존성과 인터페이스가 테스트코드 (혹은 제품 코드)에 어떤 영향을 주는지에 대한 글)

**Headless**
- [(번역) 헤드리스 컴포넌트: 리액트 UI를 합성하기 위한 패턴](https://ykss.netlify.app/translation/headless_component_a_pattern_for_composing_react_uis/)
- [Headless UI Library란?](https://blog.jbee.io/react/Headless+UI+Library%EB%9E%80%3F) (스타일은 라이브러리를 사용하는 개발자에게 위임하고 자신은 상태와 그 상태를 제어할 수 있는 인터페이스만 노출
)
- [(번역) React에서 UI와 로직 분리하기:헤드리스 컴포넌트를 사용한 클린 코드 접근법](https://soobing.github.io/react/decoupling-ui-and-logic-in-react-a-clean-code-approach-with-headless-components/)
- 3개다 헤드리스 컴포넌트가 무엇이고, 어떤 장점이 있는지 예제를 통해 설명하는 글 

### 기타

관련 작업들은 우선 [base/faq-refactor 브랜치](https://github.com/depromeet/www.depromeet.com/tree/base/faq-refactor)에 머지할게요! 여유로울 때 가볍게 봐주시면 진짜 너무 고마울 듯~~~ 🙇
(코드 리뷰,,, 해준다면 진짜 착한 사람)

**Comment by sumi-0011** [comment]
😇
