### ISSUE TITLE
아이패드 12.9 인치에서 사이트가 짤려서 보여요

### ISSUE THREAD

**Issue by gomjellie** [depromeet/www.depromeet.com#74]
![0AF077DF-63CC-4B24-9B5E-96F80FF0D615](https://user-images.githubusercontent.com/13645032/173837586-e7845046-4167-4c62-bedf-d16cea73d281.png)

**Comment by pumpkiinbell** [comment]
@gomjellie ㅋㅋㅋㅋㅋㅋㅋ 제보 감사합니다 수정할게요 👍🏻

**Comment by pumpkiinbell** [comment]
요거는... 테블릿 대응 디자인이 필요한데 11 기 세션이 거의 끝나가서 당장 대응은 어렵겠네요 😭 
다음 운영진 분들에게 홈페이지 전반적으로 테블릿 대응이 필요하다고 꼭 전달하도록 하겠습니다

**Comment by hyesungoh** [comment]
안녕하세요! 12기 운영진을 맡은 오혜성입니다 😄 

해당 이슈 확인하였으며, 참고하여 개발 해보겠습니다 ! 🗡️ 

> 이슈는 close 하겠습니다!
