### ISSUE TITLE
헤더 11기에서 만나기 버튼 정렬확인!

### ISSUE THREAD

**Issue by silverchoic2** [depromeet/www.depromeet.com#77]
<img width="201" alt="스크린샷 2022-06-19 오후 9 54 45" src="https://user-images.githubusercontent.com/107799192/174481958-ad6c6534-21a1-4c0e-a145-6a9e21d002da.png">
현재 위쪽으로 올라가 있슴돠!

**Comment by pumpkiinbell** [comment]
v2.2.1 에 반영되었습니다 🙂 

https://github.com/depromeet/www.depromeet.com/releases/tag/v2.2.1
